package se.chalmers.dcs.spe.simulation;

/**
 * Interface for defining metrics that can help with scheduling decisions.
 *
 */
public interface OperatorMetric {
	/**
	 * Update the metric value after some time of executing the operator.
	 * 
	 * @param time
	 *            The current (simulation) time.
	 * @param inputQueueSize
	 *            The size of the input queue of the operator.
	 * @param processedTuples
	 *            The number of processed tuples since the last call to this
	 *            function.
	 * @param outputTuples
	 *            The tuples generated by the operator since the last call to this
	 *            function.
	 */

	void update(long time, long inputQueueSize, long processedTuples, long outputTuples);

	/**
	 * Get the value of the metric, based on the values reported so far.
	 * 
	 * @return The value of the metric.
	 */
	double getValue();
}
